name: Check pull request

on:
  pull_request:
    branches: [ main, develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          check-latest: true
        
      - name: Install dependencies
        run: npm ci
        
      - name: Run lint
        run: npm run lint
      
      - name: Run unit tests
        run: npm run test
